### ISSUE TITLE
Archivalien: Freitextsuche Feld Datierung 

### ISSUE THREAD

**Issue by CranacharchivGunnar** [lucascranach/cranach-api#143]
### URL of the buggy page?

https://lucascranach.org/artefacts/de/DE_SLGSW_II3_4157/

### Contact Details

gunnar.heydenreich@th-koeln.de

### What happened?

Wenn ich im Freitext Suchfeld eingebe: "1531", dann müsste ich doch z.B. den 1531 datierten Datensatz 
https://lucascranach.org/artefacts/de/DE_SLGSW_II3_4157/
angezeigt bekommen (Datierung 1531 Januar 18 ), findet er aber nicht. (Findet nur Datensätze, wo "1531" unten im Textfeld auftaucht)
Vermutlich muss das Feld "Datierung" noch in die Freitextsuche einbezogen werden... (auch wenn das keine Zeiträume filtern kann, so wie die dafür besser geeignete Filterfunktion "Datierung")

**Comment by cnoss** [comment]
@vschaefer wie ist hier der Stand?

**Comment by vschaefer** [comment]
@CranacharchivGunnar Die Änderungen sind jetzt auf dem Liveserver. Bitte schau einmal ob es jetzt besser ist.

**Comment by CranacharchivGunnar** [comment]
Hi Volker,
sorry, Online ist immer noch die alte Reihenfolge der Archivalien sichtbar. Im internen Bereich Vorschau ist sie korrekt...

**Comment by vschaefer** [comment]
Hallo Gunnar,

hier geht es um die Freitextsuche und nicht um die Reihenfolge :-)

**Comment by CranacharchivGunnar** [comment]
OK, sorry, bei Archivalien denke ich nur noch an Reihenfolge...
Also auch hier leider NEIN:
https://lucascranach.org/de/DE_SLGSW_II3_4157
wird bei Freitextsuche "1531" immer noch nicht gefunden, obwohl 1531 Januar 18 datiert.
G

**Comment by vschaefer** [comment]
@CranacharchivGunnar Ich hatte den Fehler behoben, aber die Anpassungen noch nicht auf den Server gezogen. Jetzt sollte der Fehler (endlich) behoben sein.

**Comment by CranacharchivGunnar** [comment]
Danke Dir, Volker! 
Alles eine Frage der Perspektive: Wenn ein Kind nach 8 Monaten die Welt erblickt, wird es als Frühchen bezeichnet.
